

platform :ios, '7.0'

pod 'MBProgressHUD', '~> 0.9.2'

pod 'AFNetworking', '~> 3.0.4'

pod 'YYModel', '~> 1.0.1'

pod 'MJRefresh', '~> 3.1.0'

pod 'SDWebImage', '~> 3.7.5'

pod 'MMDrawerController', '~> 0.6.0'

